app:
  theme: "light"

canvas:
  info: "#000000"
  name: "black"
  name_inchess: "red"
  name_onmove: "green"
  background: "#ffffff"
  font-family: "Roboto"
  game_over: "black"

board:
  last_move: "#000000"
  valid_move: "green"
  selection: "#ffffff"
  attack_move: "red"
  hex_color:
    - "#a8baf0"
    - "#f0b6a8"
    - "#d1f0a8"
  hex_inchess: "#ff0000"
  hex_alpha: "a8"
  hint_lines: "#ffffff"

pieces:
  font-family: "Verdana"
  stroke-color: "white"
  color:
    - "#000599"
    - "#b33900"
    - "#1d6600"
