canvas:
  info: "#ffffff"
  name: "black"
  name_inchess: "red"
  name_onmove: "green"
  background: "#ffffff"
  font-family: "Arial"
  game_over: "black"

board:
  last_move: "black"
  valid_move: "green"
  attack_move: "red"
  hex_color:
    - "#a8baf0"
    - "#f0b6a8"
    - "#d1f0a8"
  hex_inchess: "red"

pieces:
  font-family: "Verdana"
  stroke-color: "white"
  color:
    - "#000599"
    - "#b33900"
    - "#1d6600"
