board:
  background: "#ffffff"
  font-family: "Arial"
  name_color: "black"
  name_color_inchess: "red"
  name_color_onmove: "green"
  last_move: "black"
  valid_move: "green"
  attack_move: "red"
  game_over: "black"

hex:
  color:
    - "#a8baf0"
    - "#f0b6a8"
    - "#d1f0a8"

pieces:
  font-family: "Verdana"
  stroke-color: "white"
  color:
    - "#000599"
    - "#b33900"
    - "#1d6600"
